### ISSUE TITLE
Can not build for WebGL

### ISSUE THREAD

**Issue by Sekaiichi4** [Unity-Technologies/ProjectTinySamples#5]
I opened the project in Unity 2019.3.0f3 and everything worked fine in the Windows build mode. I am however getting the following errors when I switch my platform to WebGL;

> Library\PackageCache\com.unity.tiny.rendering@0.20.0-preview.3\Runtime\Unity.Tiny.Rendering.Native\RendererBGFX.cs(12,18): error CS0234: The type or namespace name 'Web' does not exist in the namespace 'Unity.Tiny' (are you missing an assembly reference?)

> Library\PackageCache\com.unity.tiny.rendering@0.20.0-preview.3\Runtime\Unity.Tiny.Rendering.Native\ShadersBGFX.cs(12,18): error CS0234: The type or namespace name 'Web' does not exist in the namespace 'Unity.Tiny' (are you missing an assembly reference?)

**Comment by Sekaiichi4** [comment]
Nvm, I figured out that I need to use the new build manager to make builds.

**Comment by jcunity** [comment]
User figured it out.

**Comment by RodwelJunior09** [comment]
Can you help me I have the same problem, right now
